# Generated by Django 3.1 on 2020-11-04 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mini_crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='order',
            name='counter',
            field=models.IntegerField(),
        ),
    ]
