# Generated by Django 3.1 on 2020-11-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_clothes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='good',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
