# Generated by Django 3.1 on 2020-11-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_clothes', '0002_auto_20201105_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaldata',
            name='label',
            field=models.CharField(max_length=300),
        ),
    ]
