# Generated by Django 3.1 on 2020-11-05 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale_clothes', '0007_auto_20201105_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='select',
        ),
    ]
