# Generated by Django 3.1.2 on 2020-10-29 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('figma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovary',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='figma.category'),
        ),
    ]
