# Generated by Django 3.1.2 on 2020-10-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figma', '0003_auto_20201029_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
