# Generated by Django 3.1.2 on 2020-10-31 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figma', '0005_auto_20201031_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='description',
            field=models.TextField(default='описание', max_length=30),
        ),
        migrations.AlterField(
            model_name='good',
            name='detail',
            field=models.TextField(default='подробности', max_length=30),
        ),
    ]
