# Generated by Django 3.1.2 on 2020-10-31 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figma', '0006_auto_20201031_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='description',
            field=models.TextField(default='Описание', max_length=30),
        ),
        migrations.AlterField(
            model_name='good',
            name='detail',
            field=models.TextField(default='Доставка и Возврат', max_length=30),
        ),
    ]
