# Generated by Django 3.1.2 on 2020-10-31 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figma', '0007_auto_20201031_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='ShippingReturns',
            field=models.TextField(default='Доставка и Возврат', max_length=30),
        ),
        migrations.AlterField(
            model_name='good',
            name='detail',
            field=models.TextField(default='Подробности', max_length=30),
        ),
    ]
