# Generated by Django 3.1.2 on 2020-10-31 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('figma', '0008_auto_20201031_0718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='good',
            old_name='ShippingReturns',
            new_name='Shipping_Returns',
        ),
    ]
