# Generated by Django 3.1 on 2020-10-29 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management_site', '0002_remove_site_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management_site.category'),
        ),
    ]
