# Generated by Django 3.1 on 2020-10-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_site', '0003_site_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
    ]
